### ISSUE TITLE
listme installation

### ISSUE THREAD

**Issue by AaronKannon** [mathpn/rememberme#8]
I'm writing this issue due to following the installation tutorial in the README.
Still in my bash, it says that the command listme is not being found.
So I think that maybe it's some problem or missing step
Or the famous "When a user tries to use my product, he immediately brokes it"
So that's why the issue here.

SO: Ubuntu 22.04.3 LTS
git version 2.34.1

**Comment by mathpn** [comment]
If you've used `go install` and your Go version is >=1.8, Go uses a default value for the environment variable GOPATH if it's not set. There's more information [here](https://go.dev/doc/go1.8#gopath). To check the value of GOPATH:

```bash
go env GOPATH
```

Binaries are installed to `$GOPATH/bin` by default (see [here](https://go.dev/doc/code))
It's likely that all you need is to add the bin directory to your PATH variable:

```bash
echo "export PATH=$PATH:$HOME/go/bin/" >> ~/.bashrc
```

If you don't use `bash` as your shell, change the destination config file accordingly. You may have to close and open your terminal to reload the config file.

**Comment by mathpn** [comment]
I've added a SETUP.md with these instructions and README now points to this file. Closing the PR will close this issue. If you still have issues, just reopen this issue 😉

**Comment by AaronKannon** [comment]
Just to say, it worked fine. Thank you for the support :smiley:
